### ISSUE TITLE
nothing returning in drop downs for configuration of task

### ISSUE THREAD

**Issue by wadehephner** [MicrosoftPremier/VstsExtensions#118]
I have just installed the extension and I am using it in a pipeline, however when i add the task there are no projects in the team project drop down and it does not seem to see all of my other projects within my organization.

thanks,
wade

**Comment by ReneSchumacher** [comment]
Hi @wadehephner,

I assume you're talking about the Create Work Item task, right? Could you tell me, where you installed it? Is it Azure DevOps Service (cloud) or Azure DevOps Server/Team Foundation Server (on-prem)?

**Comment by wadehephner** [comment]
Hello, sorry yes, I should have supplied that. It is the Create work item task and it is in azure devops cloud.

**Comment by wadehephner** [comment]
Hello @ReneSchumacher do you have any update on this issue?

thanks,
-wade

**Comment by ReneSchumacher** [comment]
Hi Wade,

sorry for the delay, I'm currently on vacation ;-) Could you please remove the extension and reinstall it, just to make sure that this is not caused by some installation issue.

Could you then please open the following URL in your browser and check if it returns your projects: `https://dev.azure.com/{your organization}/_apis/projects?$top=1000&api-version=3.0`

**Comment by wadehephner** [comment]
Hello Rene, sorry about bothering you on vacation, I removed and reinstalled the extension, and the url does return a list of projects, however in the pipeline it still does not return the project list.

thanks,
-wade

**Comment by ReneSchumacher** [comment]
Hi Wade,

sorry again for the delay (still on vacation and not checking my work mail regularly). This is indeed pretty strange. Could you please try the following steps:

1. Create a new empty classic build pipeline.
2. Add the _Create Work Item_ task to the pipeline.
3. Open the developer tools in your browser by pressing F12 (should work in all browsers but I suggest using either Google Chrome or the new Microsoft Edge based on the Chromium engine).
4. Switch to the _Network_ tab of the developer tools and click the _Clear_ button (second from the left, black circle):
   ![image](https://user-images.githubusercontent.com/11600642/94543620-95438e00-024a-11eb-817b-dc09561f2a70.png)
5. Click the _Refresh_ button next to the _Team Project_ field in the _Create Work Item_ task UI:
   ![image](https://user-images.githubusercontent.com/11600642/94543825-d045c180-024a-11eb-8918-6cf249654cfb.png)
6. After clicking the _Refresh_ button you should see a call to the Azure DevOps backend in the developer tool's _Network_ tab. Click the _Export HAL_ button to save the information of the call:
   ![image](https://user-images.githubusercontent.com/11600642/94544071-1733b700-024b-11eb-8fa0-fa030b4a1794.png)
7. Send the saved _.har_ file to PSGerExtSupport@microsoft.com so I can take a closer look at what's going on.

**Comment by wadehephner** [comment]
Hello Rene, no worries on the vacation, enjoy your time off. I did want to send you a screen shot because I do not see what you are showing in your images. I create a new build pipeline and go to add the Create Work Item task however I do not see a refresh button next to team project. When i create a release pipeline the extension is working fine, it is in the build pipeline where I wish to use this extension and that is where is it not working. please see my attached screen shot.

![image](https://user-images.githubusercontent.com/61989010/94574148-6b816b80-0238-11eb-855c-2128d034a703.png)

**Comment by ReneSchumacher** [comment]
Aah, now I see what's going on :)

You are using the task helper UI while creating a YAML pipeline. Unfortunately, that UI does not have the same capabilities as the classic pipeline UI. It cannot make REST calls, which is why it is neither showing the team projects nor the refresh button. In addition, the task helper UI does not support custom task editors, which is why you don't see the ellipsis (triple dot) button next to _Area Path_, _Iteration Path_, and _Additional Fields_.

All of those UI features are not supported by the task helper UI. You can still enter values in the UI (except for the team project) and add the YAML snippet to your pipeline definition. Afterwards, you have to add any missing values directly in YAML. A full list of all YAML settings can be found at https://github.com/MicrosoftPremier/VstsExtensions/blob/master/CreateWorkItem/en-US/overview.md#adding-the-task-to-a-yaml-definition.

Hope that helps.

**Comment by wadehephner** [comment]
ah well now that all makes sense. thanks for the clarification. I appreciate your time.
