### ISSUE TITLE
BuildQualityChecks task transiently thinks that the code coverage for a build is 0%.

### ISSUE THREAD

**Issue by grantborthwick** [MicrosoftPremier/VstsExtensions#14]
![image](https://user-images.githubusercontent.com/2301725/45329971-ea06f580-b517-11e8-90aa-ff4fe040e9ad.png)

**Comment by ReneSchumacher** [comment]
Hi Grant,

thanks for reporting this. I believe this issue has already been fixed with version 5.x. Could you please update the task to the latest version and run your build again? If the problem persists, please run the build again with the variables System.Debug and BQC.LogRawData set to true and send us the task log via email to PSGerExtSupport (at) microsoft.com. Please check the log file for any sensitive information before sending it in.

Thanks
René

**Comment by grantborthwick** [comment]
I've updated to version 5.x, and it appears to be working. I'll send logs if I see failures. Thanks, René!
