### ISSUE TITLE
Check-in is taking more time to complete when compared to last week and sometimes build quality is getting failed with covered lines: 0

### ISSUE THREAD

**Issue by nithinpuch** [MicrosoftPremier/VstsExtensions#140]
![corebuild2](https://user-images.githubusercontent.com/26786144/112506009-91e91500-8d4a-11eb-9d4c-66005c0c5743.png)
[corebuildlog2.txt](https://github.com/MicrosoftPremier/VstsExtensions/files/6206221/corebuildlog2.txt)

Check build quality step is failing intermittently and re-trying it couple of times the step is getting succeeded. Need to know the reason behind intermittent failure with no issue.

**Comment by nithinpuch** [comment]
@ReneSchumacher Can you comment on this when you got some time

**Comment by ReneSchumacher** [comment]
Hi @nithinpuch,

intermittent issues with the Build Quality Checks tasks are usually caused by slow asynchronous processing of coverage data, which then leads to timeouts. However, you seem to be hitting a different problem as the log shows `Invalid Resource`. Without additional information it's impossible to tell the root cause for this. In addition, you seem to be using a fairly old version of the task. The current version is v8.1.0 and has a couple bug fixes and improvements.

Could you please try updating to the latest version and then run your build with the variables `System.Debug` and `BQC.LogRawData` set to `true`? Once the pipeline fails again with this log message, the log should contain additional information about where it's failing and about the coverage data the task might have read from the backend.

**Comment by nithinpuch** [comment]
@ReneSchumacher thanks for the insights. I will do the needful and get back to you if i need further help on this.

**Comment by nithinpuch** [comment]
@ReneSchumacher i see the latest version as 6 and i don't see version 8 as you mentioned. Am i missing something? see the pic below.

![image](https://user-images.githubusercontent.com/26786144/113209269-af751d80-9227-11eb-9c07-93ad67153623.png)

**Comment by ReneSchumacher** [comment]
Hi @nithinpuch,

did the update to the latest version as described in my email resolve the issue?

**Comment by ReneSchumacher** [comment]
Closing due to lack of feedback.
