### ISSUE TITLE
BQC task failing with Cannot read null property in Azure Devops pipeline

### ISSUE THREAD

**Issue by AnushaCha** [MicrosoftPremier/VstsExtensions#151]
Hi Rene,

Hope you are doing good.
We are still struggling with the BQC task failure in our ADO pipeline.
Similar issue has been raised in the past. https://github.com/MicrosoftPremier/VstsExtensions/issues/131
Now the BQC task fails with error Cannot read property 'records' of null
Could you please help me out.
Let me know any other information needed.

Thanks,
Anusha Challagali

**Comment by ReneSchumacher** [comment]
Hi @AnushaCha,

can you run your pipeline again with `System.Debug` and `BQC.LogRawData` set to `true` and send me the log file to PSGerExtSupport@microsoft.com? I need to know which version of BQC you're using, what the "context" of the task is and if there might be a special data constellation in your pipeline. Errors like this sometimes arise due to changes in Azure DevOps that we need to adapt our task to.

**Comment by AnushaCha** [comment]
Hi Rene,

I have send the logs and some more details to PSGerExtSupport@microsoft.com
Kindly have a look.

Thanks,
Anusha Challagali

**Comment by ReneSchumacher** [comment]
Hi @AnushaCha,

as mentioned via email, we just released v8.1.2 of the BQC task that should be more robust when it comes to intermittent connectivity issues with Azure DevOps. I'm closing the issue here, but we can keep up the conversation via email.
