### ISSUE TITLE
Build Quality Checks 

### ISSUE THREAD

**Issue by Kareem4006** [MicrosoftPremier/VstsExtensions#176]
**Describe the context**
- **Extension:**  BuildQualityChecks,
- **Environment:**  Azure DevOps/Team Foundation Server (on-prem)?*
  - **Server version:** 
- **Agent type:** *Microsoft-hosted 
  - **Agent version:** 
- **Pipeline type:** * classic build

Hello, Team

Builds have failed due to the following error
[WARNING] connect ETIMEDOUT 13.107.42.20:443
##[warning]connect ETIMEDOUT 13.107.42.20:443
Total blocks: 0
Covered blocks: 0
Code Coverage (%): 0
[ERROR] The code coverage value (0%, 0 blocks) is lower than the minimum value (80%)!
##[error]The code coverage value (0%, 0 blocks) is lower than the minimum value (80%)!
Finishing: Check build quality

Are there any recommendations to solve this problem?

Thanks in advance 😃

**Comment by ReneSchumacher** [comment]
Hi @Kareem4006,

thanks for sending over the pipeline log. It seems like you have set a timeout for the task for two minutes, which may be too short for the task to get the code coverage data from Azure DevOps. After you have published your coverage data, which is automatically done by the VS Test task, it has to be processed by Azure DevOps first before our task can download the data and inspect it. Thus, we have a built-in waiting mechanism with built-in timeouts (default is ten minutes). If you now specify a shorter timeout, the agent will cancel our task before it can download and inspect the data, which sometimes can take some time. Please either increase the timeout for the task or remove it.

In addition, I can see that your VS Test task does not have code coverage enabled. Please check that as well and make sure that you can see coverage values in your pipeline summary view. Otherwise, our task will run into the internal timeout as there is no data to read.

**Comment by Kareem4006** [comment]
@ReneSchumacher I've edited the build and I sent you the pipeline log.

**Comment by ReneSchumacher** [comment]
Hi again,

I have inspected the new log file and the task seems to be working now. It fails because you configured a threshold of 10% coverage but your coverage is at 0% (0 of 10 blocks). According to the log, no tests have been executed due to a framework mismatch. You should ensure that tests are properly executed and you can see test results and coverage data in the build summary view before you add Build Quality Checks to your pipeline.

**Comment by ReneSchumacher** [comment]
Hi @Kareem4006,

do you have any update for this issue? Or is it resolved and can be closed?

**Comment by Kareem4006** [comment]
Thank you for your follow up, It can be closed now
