### ISSUE TITLE
task version CreateWorkItem fails

### ISSUE THREAD

**Issue by lenisha** [MicrosoftPremier/VstsExtensions#23]
Getting message after installing the createworkitem extension
"Job Failure: Step  references task 'CreateWorkItem' at version '1' which does not exist."

jobs:
- job: Build
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'dotnet test'
    inputs:
      command: test
      workingDirectory: apis/poi

- job: Failure
  dependsOn: Build
  condition: failed() # this job will only run if Build fails
  steps:
   - task: CreateWorkItem@1
    displayName: 'Create work item'
    inputs:
      workItemType: Bug
      title: 'Build $(build.buildNumber) failed'

**Comment by lenisha** [comment]
Found the issue- it run only on windows image (not ubuntu)

**Comment by ReneSchumacher** [comment]
Hi Elena,

all our tasks work on all types of build agents (Windows, Linux, MacOS). There currently are some issues with extensions on Azure DevOps that the product teams are already investigating. If you get the error message that a build task from an extension does not exist even though you installed the extension, please try disabling and reenabling the extension. This has worked for multiple other users and seems to be a simple workaround until the product teams have fixed the issue.

Please check again and let me know if it works. Otherwise I'm more than happy to investige why you're not able to run the task on Ubuntu.

René

**Comment by ReneSchumacher** [comment]
Hi Elena,

since I haven't received any additional feedback, I'm closing the issue for now. If you still need help with running our task on Linux, please reopen the issue and let us know.

Happy building!
René
