### ISSUE TITLE
[BuildQualityChecks] Add logging for policy violations

### ISSUE THREAD

**Issue by simondel** [MicrosoftPremier/VstsExtensions#52]
## Expected behavior
Each violated rule is logged as an error to prevent a mandatory navigation to the Summary tab in Azure DevOps.

In my opinion, the Build Quality Checks section in the Summary tab only offers a better experience if you have multiple jobs with errors. For a single job with errors, looking at logs would be easier.

## Actual behavior
Users have to navigate to the Build Quality Checks section to see the results.
![image](https://user-images.githubusercontent.com/4221997/68294640-ef66be00-0090-11ea-9c15-1358f55e401d.png)

**Comment by ReneSchumacher** [comment]
Hi Simon,

sorry for the delayed reply and thanks for the suggestion. We will change the task in the upcoming version so you can see warnings and errors in the build issue list. Since that list is limited (only the first couple of issues are actually listed) you still might have to go to the task's summary section in some cases, though. We unfortunately cannot change that behavior.

René

**Comment by simondel** [comment]
That already sounds like a big improvement, thanks!

**Comment by ReneSchumacher** [comment]
Hi @simondel,

we haven't been able to work on the task as the last two month have been pretty busy. Yet, the good news is that I just updated the task to properly log warnings and errors as build issues. I have a couple other things on the backlog that I want to include in the next release but you can expect a new version with your requested changes either by tomorrow or early next week. I'll post an update and close the issue once the changes are released.

René

**Comment by ReneSchumacher** [comment]
Hi again,

we have updated the logging in version 6.2.0, which was just published. Thus, I'm closing this issue now. If you need anything else, please let us know.

Happy building,
René
