### ISSUE TITLE
Is it possible to see which warnings are new when warnings policy is violated?

### ISSUE THREAD

**Issue by iansul** [MicrosoftPremier/VstsExtensions#53]
We are, unfortunately, working with a lot of existing warnings, and when the warnings policy fails it can be hard to find the new warning. Is it possible to display some or all of the "new" warnings when the policy fails?

**Comment by ReneSchumacher** [comment]
Hi!

We've been thinking about this for a while now. After parsing the log file, we have a list of all the warnings with warning ID, file, line etc. However, it is not easy to figure out which warnings are actually new warnings. Assume you have added a single code line to your file. When you build again, we see the exact same warnings but all line numbers of the warnings have changed when compared to the previous build. Yet, none of the warnings has actually changed.

In order to know exactly which warnings have changed, we'd need information about the code files for the current and the previous build. I'm still trying to figure our how to achieve this. Currently, you can only activate the warning statistics option. This provides information about the files that have changed warnings. Not as good as what you're looking for but at least a first step in the right direction.

René

**Comment by ReneSchumacher** [comment]
Hi @iansul,

I hope the warning statistics have helped tackle the problem. I have put your request on our backlog and see if we can find a way to provide more detailed information about the different warnings. As this is not a defect in the current task, I'm going to close the issue now. Please feel free to open a new one if you need anything else.

Happy building,
René

**Comment by iansul** [comment]
Will checkout the warning statistics thanks for the followup.
