### ISSUE TITLE
Zero Warning every time

### ISSUE THREAD

**Issue by raphaelmoreira** [MicrosoftPremier/VstsExtensions#62]
Morning.

I have a simple app to test how the warning works. So, I did basic configurations on at (default for everything).

My App has **9 Warning** like above:

![image](https://user-images.githubusercontent.com/5034220/72260569-e72b8180-35f1-11ea-88f2-55712c49234b.png)

My Pipeline has this step

- task: BuildQualityChecks@6
  inputs:
    checkWarnings: true
    warningFailOption: 'build'
    forceFewerWarnings: true
    showStatistics: true
    warningTaskFilters: '/^(((android|xcode|gradlew)\s+)?build|ant|maven|cmake|gulp)/i'

When I run the build, I received this:

Task         : Build Quality Checks
Description  : Breaks a build based on quality metrics like number of warnings or code coverage.
Version      : 6.1.2
Author       : Microsoft Premier Services
Help         : [[Docs]](https://github.com/MicrosoftPremier/VstsExtensions/blob/master/BuildQualityChecks/en-US/overview.md)
==============================================================================
SystemVssConnection exists true
Validating build warnings policy...
The specified task filters did not match any build task.
Found baseline build with ID 25975.
Counting warnings from tasks:
- BuildQualityChecks
-   Total warnings: 0, Filtered warnings: 0
Total warnings: 0
Filtered warnings: 0
Finishing: BuildQualityChecks

I try to change code, raise the warning, but nothing change;
I try to use regex to catch some type of warning. Nothing happens.

What kind of warning this task fetch? Someone can help me?
Thank you.

**Comment by ReneSchumacher** [comment]
Hi @raphaelmoreira,

the issue is caused by our default task filter value that does not properly match all default tasks when used in YAML pipelines. As a quick workaround you can use the following value:

`/^((vs|ms)build|ant(\\s+.+)?|gradle(w)?(\s+.+)?|grunt|gulp|maven(\s+.+)?|xamarin(android|ios)|xcode(\s+.+)?|cmake|build\s+.+)$/i`

I have already fixed the default value in our task so the issue should be gone with the next update. If all goes well, the fixed version will be available today.

René

**Comment by raphaelmoreira** [comment]
It works!
Thank you for the assistance =)
