### ISSUE TITLE
Warning detector and code signing

### ISSUE THREAD

**Issue by MatthewSteeples** [MicrosoftPremier/VstsExtensions#71]
We've started signing our assemblies as part of our build process, and when we started doing it the Build Quality task started telling us we have problems. I think it's because the code signing process outputs the following text

`Number of warnings: 0`

I'm assuming that this is what is being picked up as a "warning". We've solved it ourselves by not running signtool in verbose mode, but thought it was worth mentioning in case anyone else encounters it

**Comment by MatthewSteeples** [comment]
I may have been entirely wrong with this. I think it's now looking like an unrelated change (some of our build steps now run more than once, so I think that it's duplicating some of them that way, although that's probably to be expected)

**Comment by ReneSchumacher** [comment]
Hey Matthew,

even though the issue seems to have been caused by something else, feel free to comment again if you still believe our task does something unexpected or if this was caused by a configuration error due to misleading documentation. We've had some feedback that some of our docs need more clarification and I'd love to track those issues and get them fixed.

René
