### ISSUE TITLE
[BQC] Title of the PR status?

### ISSUE THREAD

**Issue by Bouke** [MicrosoftPremier/VstsExtensions#79]
I have setup two BQC tasks with different "Run Titles". The PR statuses are being posted, but the titles of those statuses are rather similar:

- Warnings policy passed with 4003 warning(s).
- Warnings policy passed with 200 warning(s).

Is there a way to customise these titles? Currently the only way to distinguish them in the UI is to hover the link, and it'll show the status' name.

**Comment by ReneSchumacher** [comment]
We wanted to keep the status short since there's not much space to display information. If we add the status name (or just the run title) at the beginning of the status, you might not see the important information and would have to hover even more often. Thus, I believed the hovering option was good enough. In addition, clicking the status jumps to the BQC summary section with all the detailed information.

**Comment by ReneSchumacher** [comment]
Since we haven't received any feedback on this, I'm closing this issue now. Pleae feel free to contact us again if you believe we need to change the existing functionality.
